// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    return $(document).on('click', '.container a', function(e) {
      var msg, url;
      url = $(this).attr('href');
      msg = $(this).closest('.msg');
      e.preventDefault();
      return $.ajax(url, {
        type: 'GET',
        dataType: 'json',
        data: $(this).serialize(),
        success: function(data, status, jqXHR) {
          return msg.empty().append(data.msg);
        }
      });
    });
  });

}).call(this);
